spring:
  datasource:
    url: postgresql://java_project_bd_user:g85aQmD8J6yK0Em3HaGU5bIcPPOBKfGr@dpg-csat5hij1k6c73ct30hg-a/java_project_bd
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
