spring:
  datasource:
    url: jdbc:h2:mem:myDataBase
    driverClassName: org.h2.Driver
    username: sa #${dbuser}
    password: password #${dbpass}

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true